<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputPath>..\Output\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="StreamJsonRpc" Version="2.22.23" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.CSharp" />
    </ItemGroup>
</Project>
