name: Build
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test ClassicAssist.Tests/ClassicAssist.Tests.csproj -c Release --no-build

    - name: Upload Plugin Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ClassicAssist-${{ matrix.os }}
        path: ./Output/ClassicAssist
